export const datos = [
  { id: 1, texto: 'Aprender sobre renderizado de listas en React', completada: true, prioridad: 'alta' },
  { id: 2, texto: 'Estudiar hooks de React', completada: false, prioridad: 'media' },
  { id: 3, texto: 'Practicar useState y useEffect', completada: true, prioridad: 'alta' },
  { id: 4, texto: 'Revisar componentes funcionales', completada: false, prioridad: 'baja' },
  { id: 5, texto: 'Implementar un formulario con validación', completada: true, prioridad: 'media' },
  { id: 6, texto: 'Aprender sobre contexto en React', completada: false, prioridad: 'alta' },
  { id: 7, texto: 'Configurar un proyecto con Vite', completada: true, prioridad: 'baja' },
  { id: 8, texto: 'Explorar React Router', completada: false, prioridad: 'media' },
  { id: 9, texto: 'Crear un componente reutilizable', completada: true, prioridad: 'alta' },
  { id: 10, texto: 'Optimizar el rendimiento con memo', completada: false, prioridad: 'media' },
  { id: 11, texto: 'Aprender TypeScript con React', completada: true, prioridad: 'alta' },
  { id: 12, texto: 'Configurar ESLint y Prettier', completada: true, prioridad: 'baja' },
  { id: 13, texto: 'Usar Tailwind CSS en un proyecto', completada: false, prioridad: 'media' },
  { id: 14, texto: 'Estudiar el ciclo de vida de los componentes', completada: true, prioridad: 'alta' },
  { id: 15, texto: 'Aprender sobre props y children', completada: false, prioridad: 'baja' },
  { id: 16, texto: 'Hacer un proyecto con API externa', completada: true, prioridad: 'alta' },
  { id: 17, texto: 'Practicar manejo de errores', completada: false, prioridad: 'media' },
  { id: 18, texto: 'Explorar lazy loading y suspense', completada: true, prioridad: 'baja' },
  { id: 19, texto: 'Aprender sobre testing con Jest', completada: false, prioridad: 'alta' },
  { id: 20, texto: 'Usar React Query para datos remotos', completada: true, prioridad: 'media' },
  { id: 21, texto: 'Documentar componentes con Storybook', completada: false, prioridad: 'baja' },
  { id: 22, texto: 'Crear un sistema de autenticación', completada: true, prioridad: 'alta' },
  { id: 23, texto: 'Refactorizar componentes grandes', completada: false, prioridad: 'media' },
  { id: 24, texto: 'Aprender sobre animaciones con Framer Motion', completada: true, prioridad: 'baja' },
  { id: 25, texto: 'Integrar Redux Toolkit', completada: false, prioridad: 'alta' }
];
